import urllib2

####
#	Download every episode into HI/ folder
#	May take a few hours depending on the connexion ( around 11GB )
####


filelist = [
"http://traffic.libsyn.com/hellointernet/HI_93_Final_Yes_This_One.mp3",
"http://traffic.libsyn.com/hellointernet/HI92.mp3",
"http://traffic.libsyn.com/hellointernet/HI_91.mp3",
"http://traffic.libsyn.com/hellointernet/HI90PumpkinPressure.mp3",
"http://traffic.libsyn.com/hellointernet/HI89.mp3",
"http://traffic.libsyn.com/hellointernet/HI88.mp3",
"http://traffic.libsyn.com/hellointernet/HI87.mp3",
"http://traffic.libsyn.com/hellointernet/HI86.mp3",
"http://traffic.libsyn.com/hellointernet/HI85.mp3",
"http://traffic.libsyn.com/hellointernet/HI84.mp3",
"http://traffic.libsyn.com/hellointernet/83.mp3",
"http://traffic.libsyn.com/hellointernet/82.mp3",
"http://traffic.libsyn.com/hellointernet/HI81.mp3",
"http://traffic.libsyn.com/hellointernet/80.mp3",
"http://traffic.libsyn.com/hellointernet/HI79_FromRussiaWithLove.mp3",
"http://traffic.libsyn.com/hellointernet/HI_LXXVIII.mp3",
"http://traffic.libsyn.com/hellointernet/HI77_v1_hello.mp3",
"http://traffic.libsyn.com/hellointernet/Rogue_One.mp3",
"http://traffic.libsyn.com/hellointernet/H.I._Seventy_Five.mp3",
"http://traffic.libsyn.com/hellointernet/HI74_Do_People_Read_The_Filenames.mp3",
"http://traffic.libsyn.com/hellointernet/HI73_Final_fixedv3.mp3",
"http://traffic.libsyn.com/hellointernet/HI_72_Final.mp3",
"http://traffic.libsyn.com/hellointernet/HI_71F.mp3",
"http://traffic.libsyn.com/hellointernet/70.mp3",
"http://traffic.libsyn.com/hellointernet/69.mp3",
"http://traffic.libsyn.com/hellointernet/HI68.mp3",
"http://traffic.libsyn.com/hellointernet/67v2.mp3",
"http://traffic.libsyn.com/hellointernet/66.mp3",
"http://traffic.libsyn.com/hellointernet/HI65_yes_this_one.mp3",
"http://traffic.libsyn.com/hellointernet/64.mp3",
"http://traffic.libsyn.com/hellointernet/63.mp3",
"http://traffic.libsyn.com/hellointernet/62.mp3",
"http://traffic.libsyn.com/hellointernet/61.mp3",
"http://traffic.libsyn.com/hellointernet/60.mp3",
"http://traffic.libsyn.com/hellointernet/59.mp3",
"http://traffic.libsyn.com/hellointernet/58.mp3",
"http://traffic.libsyn.com/hellointernet/57.mp3",
"http://traffic.libsyn.com/hellointernet/56.mp3",
"http://traffic.libsyn.com/hellointernet/55.mp3",
"http://traffic.libsyn.com/hellointernet/54.mp3",
"http://traffic.libsyn.com/hellointernet/53.mp3",
"http://traffic.libsyn.com/hellointernet/52.mp3",
"http://traffic.libsyn.com/hellointernet/51.mp3",
"http://traffic.libsyn.com/hellointernet/50.mp3",
"http://traffic.libsyn.com/hellointernet/The_Shortlist.mp3",
"http://traffic.libsyn.com/hellointernet/49.mp3",
"http://traffic.libsyn.com/hellointernet/48.mp3",
"http://traffic.libsyn.com/hellointernet/47.mp3",
"http://traffic.libsyn.com/hellointernet/46.mp3",
"http://traffic.libsyn.com/hellointernet/45.mp3",
"http://traffic.libsyn.com/hellointernet/44.mp3",
"http://traffic.libsyn.com/hellointernet/43.mp3",
"http://traffic.libsyn.com/hellointernet/42.mp3",
"http://traffic.libsyn.com/hellointernet/41.mp3",
"http://traffic.libsyn.com/hellointernet/40.mp3",
"http://traffic.libsyn.com/hellointernet/39.mp3",
"http://traffic.libsyn.com/hellointernet/38.mp3",
"http://traffic.libsyn.com/hellointernet/37.mp3",
"http://traffic.libsyn.com/hellointernet/36.mp3",
"http://traffic.libsyn.com/hellointernet/35.mp3",
"http://traffic.libsyn.com/hellointernet/34.mp3",
"http://traffic.libsyn.com/hellointernet/33.mp3",
"http://traffic.libsyn.com/hellointernet/32.mp3",
"http://traffic.libsyn.com/hellointernet/31.mp3",
"http://traffic.libsyn.com/hellointernet/30.mp3",
"http://traffic.libsyn.com/hellointernet/29.mp3",
"http://traffic.libsyn.com/hellointernet/28.mp3",
"http://traffic.libsyn.com/hellointernet/27.mp3",
"http://traffic.libsyn.com/hellointernet/26.mp3",
"http://traffic.libsyn.com/hellointernet/25.mp3",
"http://traffic.libsyn.com/hellointernet/24.mp3",
"http://traffic.libsyn.com/hellointernet/23.mp3",
"http://traffic.libsyn.com/hellointernet/22.mp3",
"http://traffic.libsyn.com/hellointernet/21.mp3",
"http://traffic.libsyn.com/hellointernet/20.mp3",
"http://traffic.libsyn.com/hellointernet/19.mp3",
"http://traffic.libsyn.com/hellointernet/18.mp3",
"http://traffic.libsyn.com/hellointernet/17.mp3",
"http://traffic.libsyn.com/hellointernet/16.mp3",
"http://traffic.libsyn.com/hellointernet/15.mp3",
"http://traffic.libsyn.com/hellointernet/14.mp3",
"http://traffic.libsyn.com/hellointernet/13.mp3",
"http://traffic.libsyn.com/hellointernet/12.mp3",
"http://traffic.libsyn.com/hellointernet/11.mp3",
"http://traffic.libsyn.com/hellointernet/1020Two20Dudes20Talking.mp3",
"http://traffic.libsyn.com/hellointernet/9.mp3",
"http://traffic.libsyn.com/hellointernet/8.mp3",
"http://traffic.libsyn.com/hellointernet/7.mp3",
"http://traffic.libsyn.com/hellointernet/6.mp3",
"http://traffic.libsyn.com/hellointernet/5.mp3",
"http://traffic.libsyn.com/hellointernet/HI20420--20Feedback20on20Feedback.mp3",
"http://traffic.libsyn.com/hellointernet/HI20320--20Four20Light20Bulbs.mp3",
"http://traffic.libsyn.com/hellointernet/HI20220--20Copyright20Not20Intended.mp3",
"http://traffic.libsyn.com/hellointernet/HI201.mp3"]

for i in filelist:

	print ("Episode : \n "+i)
	response = urllib2.urlopen(i)
	episode = response.read()
	with open("HI/"+str(i[40:]),"wb") as file :
		file.write( episode )